{{ if .Values.mongodb.enabled }}
{{- if not .Values.mongodb.existingPasswordSecret }}
{{- $mongodbPassword := "" }}
{{- if .Values.mongodb.password }}
  {{- $mongodbPassword = .Values.mongodb.password }}
{{- else }}
  {{- $mongodbPassword = randAlphaNum 64 }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: my-user-password
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  password: {{ $mongodbPassword | b64enc | quote}}
{{- end }}
{{ end }}
